package com.dppsmart.dppsmart.Pdf.Services;

import com.dppsmart.dppsmart.Ai.Services.ProductAiScoringService;
import com.dppsmart.dppsmart.Common.Exceptions.BadRequestException;
import com.dppsmart.dppsmart.Common.Exceptions.ForbiddenException;
import com.dppsmart.dppsmart.Common.Exceptions.NotFoundException;
import com.dppsmart.dppsmart.Employee.Entities.Employees;
import com.dppsmart.dppsmart.Employee.Repositories.EmployeesRepository;
import com.dppsmart.dppsmart.Orders.Entities.Orders;
import com.dppsmart.dppsmart.Orders.repositories.OrdersRepository;
import com.dppsmart.dppsmart.Pdf.DTO.GeneratePdfRequestDto;
import com.dppsmart.dppsmart.Pdf.DTO.PdfReportType;
import com.dppsmart.dppsmart.Product.Entities.Product;
import com.dppsmart.dppsmart.Product.Repositories.ProductRepository;
import com.dppsmart.dppsmart.Production.Entities.Production;
import com.dppsmart.dppsmart.Production.Repositories.ProductionRepository;
import com.dppsmart.dppsmart.Scan.Entities.ScanEvent;
import com.dppsmart.dppsmart.Scan.Repositories.ScanEventRepository;
import com.dppsmart.dppsmart.Security.PermissionService;
import com.dppsmart.dppsmart.Stock.Entities.Stock;
import com.dppsmart.dppsmart.Stock.Repositories.StockRepository;
import com.dppsmart.dppsmart.User.Entities.Roles;
import com.dppsmart.dppsmart.User.Entities.User;
import com.dppsmart.dppsmart.User.Repositories.UserRepository;
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service
public class PdfReportService {

    private final UserRepository userRepository;
    private final PermissionService permissionService;
    private final ProductRepository productRepository;
    private final ProductAiScoringService productAiScoringService;
    private final OrdersRepository ordersRepository;
    private final StockRepository stockRepository;
    private final ProductionRepository productionRepository;
    private final EmployeesRepository employeesRepository;
    private final ScanEventRepository scanEventRepository;

    public PdfReportService(
            UserRepository userRepository,
            PermissionService permissionService,
            ProductRepository productRepository,
            ProductAiScoringService productAiScoringService,
            OrdersRepository ordersRepository,
            StockRepository stockRepository,
            ProductionRepository productionRepository,
            EmployeesRepository employeesRepository,
            ScanEventRepository scanEventRepository
    ) {
        this.userRepository = userRepository;
        this.permissionService = permissionService;
        this.productRepository = productRepository;
        this.productAiScoringService = productAiScoringService;
        this.ordersRepository = ordersRepository;
        this.stockRepository = stockRepository;
        this.productionRepository = productionRepository;
        this.employeesRepository = employeesRepository;
        this.scanEventRepository = scanEventRepository;
    }

    public byte[] generate(String userId, GeneratePdfRequestDto req) {
        User user = userRepository.findById(userId).orElseThrow(() -> new NotFoundException("User not found"));
        if (user.getRole() != Roles.ADMIN) {
            throw new ForbiddenException("Only ADMIN can download PDF reports");
        }
        if (req == null || req.getType() == null) throw new BadRequestException("type is required");

        return switch (req.getType()) {
            case DASHBOARD_GLOBAL -> dashboardGlobal(user);
            case DASHBOARD_ORG -> dashboardOrg(user, requireOrg(req.getOrganizationId()));
            case PRODUCT_DPP -> productDpp(user, requireProduct(req.getProductId()));
            case ORDERS_ORG -> ordersOrg(user, requireOrg(req.getOrganizationId()));
            case STOCK_LOW_ORG -> stockLowOrg(user, requireOrg(req.getOrganizationId()));
            case SCANS_ANOMALIES_GLOBAL -> scanAnomaliesGlobal(user);
        };
    }

    private byte[] dashboardGlobal(User user) {
        Document doc = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("DppSmart - Global Dashboard Report"));
            doc.add(metaLine("Generated at", LocalDateTime.now().toString()));
            doc.add(metaLine("Generated by", user.getEmail()));
            doc.add(Chunk.NEWLINE);

            long products = productRepository.count();
            long orders = ordersRepository.count();
            long productions = productionRepository.count();
            long employees = employeesRepository.count();
            long scans = scanEventRepository.count();

            doc.add(section("KPIs"));
            doc.add(paragraph("- products: " + products));
            doc.add(paragraph("- orders: " + orders));
            doc.add(paragraph("- productions: " + productions));
            doc.add(paragraph("- employees: " + employees));
            doc.add(paragraph("- scans: " + scans));

            doc.add(Chunk.NEWLINE);
            doc.add(section("Low stock"));
            long low = stockRepository.findAll().stream()
                    .filter(s -> s.getQuantity() != null && s.getMinimumThreshold() != null)
                    .filter(s -> s.getQuantity() <= s.getMinimumThreshold())
                    .count();
            doc.add(paragraph("Items at/below minimum threshold: " + low));

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private byte[] dashboardOrg(User user, String orgId) {
        Document doc = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("DppSmart - Organization Dashboard Report"));
            doc.add(metaLine("OrganizationId", orgId));
            doc.add(metaLine("Generated at", LocalDateTime.now().toString()));
            doc.add(metaLine("Generated by", user.getEmail()));
            doc.add(Chunk.NEWLINE);

            long products = productRepository.findByOrganizationId(orgId).size();
            long orders = ordersRepository.findByOrganizationId(orgId).size();
            long productions = productionRepository.findByOrganizationId(orgId).size();
            long employees = employeesRepository.findByOrganizationId(orgId).size();
            long scans = scanEventRepository.findByOrganizationIdOrderByScannedAtDesc(orgId).size();

            doc.add(section("KPIs"));
            doc.add(paragraph("- products: " + products));
            doc.add(paragraph("- orders: " + orders));
            doc.add(paragraph("- productions: " + productions));
            doc.add(paragraph("- employees: " + employees));
            doc.add(paragraph("- scans: " + scans));

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private byte[] productDpp(User user, String productId) {
        Product p = productRepository.findById(productId).orElseThrow(() -> new NotFoundException("Product not found"));

        Document doc = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("Digital Product Passport"));
            doc.add(metaLine("Product ID", p.getId()));
            doc.add(metaLine("Organization ID", p.getOrganizationId()));
            doc.add(Chunk.NEWLINE);

            doc.add(section("Product"));
            doc.add(paragraph("Name: " + safe(p.getProductName())));
            doc.add(paragraph("Category: " + safe(p.getCategory())));
            doc.add(paragraph("Material: " + safe(p.getMaterial())));
            doc.add(paragraph("Certification: " + safe(p.getCertification())));
            doc.add(paragraph("DPP URL: " + safe(p.getDppUrl())));

            doc.add(Chunk.NEWLINE);
            doc.add(section("AI quality score"));
            var score = productAiScoringService.scoreProduct(p);
            doc.add(paragraph("Score: " + score.getScore() + "/100"));
            doc.add(paragraph("Summary: " + score.getSummary()));
            doc.add(paragraph("Missing fields: " + String.join(", ", score.getMissingFields())));

            doc.add(Chunk.NEWLINE);
            doc.add(section("Production steps"));
            if (p.getProductionSteps() == null || p.getProductionSteps().isEmpty()) {
                doc.add(paragraph("(no steps)"));
            } else {
                PdfPTable t = new PdfPTable(3);
                t.setWidthPercentage(100);
                t.addCell("Step");
                t.addCell("Description");
                t.addCell("Date");
                int i = 1;
                for (var s : p.getProductionSteps()) {
                    t.addCell(s == null ? String.valueOf(i++) : safe(s.getStepName()));
                    t.addCell(s == null ? "" : safe(s.getDescription()));
                    t.addCell(s == null
                            ? ""
                            : (s.getEndDate() != null
                                    ? s.getEndDate().toString()
                                    : (s.getStartDate() != null ? s.getStartDate().toString() : "")));
                }
                doc.add(t);
            }

            doc.add(Chunk.NEWLINE);
            doc.add(section("Additional info"));
            if (p.getAdditionalInfo() == null || p.getAdditionalInfo().isEmpty()) {
                doc.add(paragraph("(none)"));
            } else {
                for (var e : p.getAdditionalInfo().entrySet()) {
                    doc.add(paragraph(e.getKey() + ": " + String.valueOf(e.getValue())));
                }
            }

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private byte[] ordersOrg(User user, String orgId) {
        if (!permissionService.canAccessOrganization(user, orgId)) {
            // ADMIN has access anyway, but keep pattern consistent
        }

        List<Orders> orders = ordersRepository.findByOrganizationId(orgId);
        Document doc = new Document(PageSize.A4.rotate());
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("Orders Report"));
            doc.add(metaLine("OrganizationId", orgId));
            doc.add(metaLine("Generated at", LocalDateTime.now().toString()));
            doc.add(Chunk.NEWLINE);

            PdfPTable t = new PdfPTable(6);
            t.setWidthPercentage(100);
            t.addCell("OrderRef");
            t.addCell("ProductId");
            t.addCell("Qty");
            t.addCell("Status");
            t.addCell("CreatedAt");
            t.addCell("CreatedBy");
            for (Orders o : orders) {
                t.addCell(safe(o.getOrderReference()));
                t.addCell(safe(o.getProductId()));
                t.addCell(o.getQuantity() == null ? "" : o.getQuantity().toString());
                t.addCell(safe(o.getStatus()));
                t.addCell(o.getCreatedAt() == null ? "" : o.getCreatedAt().toString());
                t.addCell(safe(o.getCreatedBy()));
            }
            doc.add(t);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private byte[] stockLowOrg(User user, String orgId) {
        List<Stock> stocks = stockRepository.findByOrganizationId(orgId).stream()
                .filter(s -> s.getQuantity() != null && s.getMinimumThreshold() != null)
                .filter(s -> s.getQuantity() <= s.getMinimumThreshold())
                .toList();

        Document doc = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("Low Stock Report"));
            doc.add(metaLine("OrganizationId", orgId));
            doc.add(metaLine("Generated at", LocalDateTime.now().toString()));
            doc.add(Chunk.NEWLINE);

            PdfPTable t = new PdfPTable(5);
            t.setWidthPercentage(100);
            t.addCell("Material");
            t.addCell("Quantity");
            t.addCell("MinThreshold");
            t.addCell("Unit");
            t.addCell("UpdatedAt");
            for (Stock s : stocks) {
                t.addCell(safe(s.getMaterialName()));
                t.addCell(s.getQuantity() == null ? "" : s.getQuantity().toString());
                t.addCell(s.getMinimumThreshold() == null ? "" : s.getMinimumThreshold().toString());
                t.addCell(safe(s.getUnit()));
                t.addCell(s.getUpdatedAt() == null ? "" : s.getUpdatedAt().toString());
            }
            doc.add(t);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private byte[] scanAnomaliesGlobal(User user) {
        LocalDateTime since = LocalDateTime.now().minusHours(1);
        List<ScanEvent> lastHour = scanEventRepository.findByScannedAtAfter(since);
        Map<String, Long> byProduct = lastHour.stream()
                .filter(s -> s.getProductId() != null)
                .collect(Collectors.groupingBy(ScanEvent::getProductId, Collectors.counting()));
        List<Map.Entry<String, Long>> spikes = byProduct.entrySet().stream()
                .filter(e -> e.getValue() >= 50)
                .sorted((a, b) -> Long.compare(b.getValue(), a.getValue()))
                .limit(10)
                .toList();

        Map<String, Product> products = productRepository.findAllById(spikes.stream().map(Map.Entry::getKey).toList())
                .stream()
                .collect(Collectors.toMap(Product::getId, Function.identity(), (a, b) -> a));

        Document doc = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("Scan Anomaly Alerts (last hour)"));
            doc.add(metaLine("Generated at", LocalDateTime.now().toString()));
            doc.add(Chunk.NEWLINE);

            if (spikes.isEmpty()) {
                doc.add(paragraph("No scan spikes detected (threshold: 50 scans/product/hour)."));
            } else {
                PdfPTable t = new PdfPTable(3);
                t.setWidthPercentage(100);
                t.addCell("ProductId");
                t.addCell("ProductName");
                t.addCell("ScansLastHour");
                for (var e : spikes) {
                    Product p = products.get(e.getKey());
                    t.addCell(e.getKey());
                    t.addCell(p == null ? "" : safe(p.getProductName()));
                    t.addCell(String.valueOf(e.getValue()));
                }
                doc.add(t);
            }

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private String requireOrg(String orgId) {
        if (orgId == null || orgId.isBlank()) throw new BadRequestException("organizationId is required");
        return orgId;
    }

    private String requireProduct(String productId) {
        if (productId == null || productId.isBlank()) throw new BadRequestException("productId is required");
        return productId;
    }

    private Paragraph title(String s) {
        Font f = new Font(Font.HELVETICA, 18, Font.BOLD);
        Paragraph p = new Paragraph(s, f);
        p.setSpacingAfter(12);
        return p;
    }

    private Paragraph section(String s) {
        Font f = new Font(Font.HELVETICA, 13, Font.BOLD);
        Paragraph p = new Paragraph(s, f);
        p.setSpacingBefore(8);
        p.setSpacingAfter(6);
        return p;
    }

    private Paragraph paragraph(String s) {
        return new Paragraph(s, new Font(Font.HELVETICA, 11));
    }

    private Paragraph metaLine(String k, String v) {
        return new Paragraph(k + ": " + safe(v), new Font(Font.HELVETICA, 10, Font.ITALIC));
    }

    private String safe(String s) {
        return (s == null) ? "" : s;
    }
}

