package com.dppsmart.dppsmart.Orders.Entities;

public enum ClientOrderStatus {
    PENDING_REVIEW,
    WAITING_DELIVERY_DATE,
    CONFIRMED,
    STOCK_CHECKED,
    PARTIALLY_AVAILABLE,
    READY_FOR_CONFIRMATION,
    STOCK_RESERVED,
    PARTIALLY_ALLOCATED,
    WAITING_FOR_MATERIALS,
    READY_FOR_PRODUCTION,
    IN_PRODUCTION,
    PRODUCTION_COMPLETED,
    READY_FOR_DELIVERY,
    PARTIALLY_DELIVERED,
    DELIVERED,
    CANCELLED,
    BLOCKED_INSUFFICIENT_STOCK,
    BLOCKED_INSUFFICIENT_MATERIALS,
    BLOCKED_NO_BOM,
    DATE_CHANGE_REQUESTED,
    READY,
    REJECTED,
    PROCESSING
}
