package com.dppsmart.dppsmart.StockMovement.Entities;

public enum MovementType {
    PRODUCT_RESERVED,
    PRODUCT_RELEASED,
    PRODUCT_DECREASED,
    PRODUCT_PRODUCED,
    PRODUCT_DELIVERED,
    MATERIAL_RESERVED,
    MATERIAL_RELEASED,
    MATERIAL_DECREASED,
    MATERIAL_CONSUMED_FOR_PRODUCTION,
    MATERIAL_RECEIVED,
    STOCK_ADJUSTMENT
}
