spring.application.name=DppSmart

spring.config.import=optional:file:.env[.properties]
# MongoDB
spring.mongodb.uri=${MONGO_URI}
# Server
server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


n8n.webhook.user=${N8N_WEBHOOK_USER}
n8n.webhook.login=${N8N_WEBHOOK_LOGIN}

